_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50

  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 17

  ROI_HEADS:
    NUM_CLASSES: 1

SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
